# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BestSwiftRepos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestSwiftRepos
  pod 'Kingfisher', '~> 4.0'
  pod 'SnapKit', '~> 5.0.0'


  target 'BestSwiftReposTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BestSwiftReposUITests' do
    # Pods for testing
  end

end
